site_name: Mixed Traffic Control
site_author: Yanzhi Yao
repo_url: https://github.com/Renoyyz233/test
edit_uri: edit/main/docs/index.md
nav:
    - Welcome: index.md
    - Smoothing traffic flow: smoothing_traffic_flow.md
    - Structured optimal control: structured_optimal_control.md
    - Cooperative formation multiple: cooperative_formation_multiple.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
